#!/bin/sh

#rm images
cd /mnt/8TB/x86_64_minipc/images
rm *.img

#rm builder
cd /mnt/8TB/x86_64_minipc/
rm -Rv /mnt/8TB/x86_64_minipc/builder
rm  *.tar.zst

#Official Snapshot
rm openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst
wget https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst

#Extract and remove snap
zstd -d openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst
tar -xvf openwrt-imagebuilder-x86-64.Linux-x86_64.tar
rm openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-x86-64.Linux-x86_64.tar
clear

#Move snapshot
mv /mnt/8TB/x86_64_minipc/openwrt-imagebuilder-x86-64.Linux-x86_64 /mnt/8TB/x86_64_minipc/builder

#Prep Directories
cd /mnt/8TB/x86_64_minipc/builder/target/linux/x86
rm *.gz
cd /mnt/8TB/x86_64_minipc/builder/target/linux/x86/image
rm *.img
cd /mnt/8TB/x86_64_minipc/builder
clear

#Config Files
rm -Rv /mnt/8TB/x86_64_minipc/builder/files
cp -R /mnt/8TB/x86_64_minipc/files.backup /mnt/8TB/x86_64_minipc/builder
mv /mnt/8TB/x86_64_minipc/builder/files.backup /mnt/8TB/x86_64_minipc/builder/files 
cd /mnt/8TB/x86_64_minipc/builder/files/
tar -xvzf *.tar.gz 
cd /mnt/8TB/x86_64_minipc/builder
rsync -av /mnt/8TB/x86_64_minipc/files.backup /mnt/1TB/x86_64_minipc
rsync -av /mnt/8TB/x86_64_minipc/files.backup /mnt/8TB/x86_64_minipc
clear

#Resize Partitions
sed -i 's/CONFIG_TARGET_KERNEL_PARTSIZE=.*/CONFIG_TARGET_KERNEL_PARTSIZE=32/' .config
sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=.*/CONFIG_TARGET_ROOTFS_PARTSIZE=400/' .config

#Build OpenWRT
make clean
make image RELEASE="" FILES="files" PACKAGES="blkid bmon htop ifstat iftop iperf3 iwinfo lsblk lscpu lsblk losetup resize2fs nano rsync rtorrent tcpdump adblock arp-scan blkid bmon kmod-usb-storage kmod-usb-storage-uas rsync kmod-fs-exfat kmod-fs-ext4 kmod-fs-ksmbd kmod-fs-nfs kmod-fs-nfs-common kmod-fs-nfs-v3 kmod-fs-nfs-v4 pppoe-discovery kmod-pppoa comgt ppp-mod-pppoa rp-pppoe-common luci luci-app-adblock luci-app-adblock-fast luci-app-commands luci-app-ddns luci-app-firewall luci-app-nlbwmon luci-app-opkg luci-app-samba4 luci-app-softether luci-app-statistics luci-app-unbound luci-app-upnp luci-app-watchcat block-mount ppp kmod-pppoe ppp-mod-pppoe luci-proto-ppp luci-proto-pppossh luci-proto-ipv6" DISABLED_SERVICES="adblock banip gpio_switch lm-sensors softethervpnclient"

#mv img's
cd /mnt/8TB/x86_64_minipc/builder/bin/targets/x86/64/
rm *squashfs*
gunzip *.img.gz
mv *.img /mnt/8TB/x86_64_minipc/images/snap
ls /mnt/8TB/x86_64_minipc/images/snap | grep raw
cd /mnt/8TB/x86_64_minipc/

############BUILD VM#######################

#!/bin/bash

# Define variables
VM_ID=101
VM_NAME="OpenWRT-Prox-Snap"
VM_MEMORY=256
VM_CPU=4
VM_DISK_SIZE="500M"
VM_NET="model=virtio,bridge=vmbr0,macaddr=BC:24:11:F8:BB:28"
VM_NET_a="model=virtio,bridge=vmbr1,macaddr=BC:24:11:35:C1:A8"
STORAGE_NAME="local-lvm"
VM_IP="192.168.1.1"
PROXMOX_NODE="PVE"

#Stop 101
qm stop 101

#Delete 101
qm destroy 101

# Create new VM
qm create $VM_ID --name $VM_NAME --memory $VM_MEMORY --net0 $VM_NET --net1 $VM_NET_a --cores $VM_CPU --ostype l26 --sockets 1

# Remove default hard drive
qm set $VM_ID --scsi0 none

# Lookup the latest stable version number
#regex='<strong>Current Stable Release - OpenWrt ([^/]*)<\/strong>'
#response=$(curl -s https://openwrt.org)
#[[ $response =~ $regex ]]
#stableVersion="${BASH_REMATCH[1]}"

# Rename the extracted img
rm /mnt/8TB/x86_64_minipc/images/snap/openwrt.raw
mv /mnt/8TB/x86_64_minipc/images/snap/openwrt-x86-64-generic-ext4-combined.img /mnt/8TB/x86_64_minipc/images/snap/openwrt.raw

# Increase the raw disk to 1024 MB
qemu-img resize -f raw /mnt/8TB/x86_64_minipc/images/snap/openwrt.raw $VM_DISK_SIZE

# Import the disk to the openwrt vm
qm importdisk $VM_ID /mnt/8TB/x86_64_minipc/images/snap/openwrt.raw $STORAGE_NAME

# Attach imported disk to VM
qm set $VM_ID --virtio0 $STORAGE_NAME:vm-$VM_ID-disk-0.raw

# Set boot disk
qm set $VM_ID --bootdisk virtio0
