#!/bin/sh

#rm images
cd /mnt/1TB_internal/x86_64_minipc/images/snap
rm *.img

#rm builder
cd /mnt/1TB_internal/x86_64_minipc/
rm -Rv openwrt-imagebuilder-x86-64.Linux-x86_64.tar*
rm -Rv /mnt/1TB_internal/x86_64_minipc/builder

#Snapshot
wget https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst

#Extract and remove snap
zstd -d openwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst
tar -xvf openwrt-imagebuilder-x86-64.Linux-x86_64.tar
rm *.zst
rm *.tar
clear

#Move snapshot
mv /mnt/1TB_internal/x86_64_minipc/openwrt-imagebuilder-x86-64.Linux-x86_64 /mnt/1TB_internal/x86_64_minipc/builder
chmod -R 777 /mnt/1TB_internal/x86_64_minipc/builder

#Prep Directories
cd /mnt/1TB_internal/x86_64_minipc/builder
clear

#Config Files
cp -R /mnt/1TB_internal/x86_64_minipc/files.backup /mnt/1TB_internal/x86_64_minipc/builder
mv /mnt/1TB_internal/x86_64_minipc/builder/files.backup /mnt/1TB_internal/x86_64_minipc/builder/files
chmod -Rvvv 777 /mnt/1TB_internal/x86_64_minipc/builder/files
cd /mnt/1TB_internal/x86_64_minipc/builder/files
tar -xvzf *.tar.gz
cd /mnt/1TB_internal/x86_64_minipc/builder
clear

#Resize Partitions
sed -i 's/CONFIG_TARGET_KERNEL_PARTSIZE=.*/CONFIG_TARGET_KERNEL_PARTSIZE=32/' .config
sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=.*/CONFIG_TARGET_ROOTFS_PARTSIZE=500/' .config

chmod -R 755 /mnt/1TB_internal/x86_64_minipc/builder/packages

#Build OpenWRT
make clean
make image RELEASE="" FILES="files" PACKAGES="blkid bmon htop ifstat iftop iperf3 iwinfo lsblk lscpu lsblk losetup resize2fs nano rsync rtorrent tcpdump arp-scan blkid bmon kmod-usb-storage kmod-usb-storage-uas rsync kmod-fs-exfat kmod-fs-ext4 kmod-fs-ksmbd kmod-fs-nfs kmod-fs-nfs-common kmod-fs-nfs-v3 kmod-fs-nfs-v4 comgt luci luci-app-commands luci-app-ddns luci-app-firewall luci-app-nlbwmon luci-app-opkg luci-app-softether luci-app-upnp luci-app-watchcat block-mount luci-proto-ipv6" DISABLED_SERVICES="banip gpio_switch lm-sensors softethervpnclient ethtool" 

#mv img's
cd /mnt/1TB_internal/x86_64_minipc/builder/bin/targets/x86/64/
rm *squashfs*
gunzip *.img.gz
mv *.img /mnt/1TB_internal/x86_64_minipc/images/snap
cd /mnt/1TB_internal/x86_64_minipc/

############ USER PROMPT #######################
echo ""
read -p "Image build complete. Do you want to proceed with building VM 101? (y/n): " confirm

# Check for "no" response first to exit safely
if [[ $confirm != [yY] && $confirm != [yY][eE][sS] ]]; then
    echo "Exiting script. VM 101 was not created." 
    exit 0 
fi
################################################

############ BUILD VM #######################

# Clean up existing VM 101 ONLY if user confirmed "yes"
qm stop 101 
qm destroy 101 

# Define variables
VM_ID=101 
VM_NAME="OpenWRT-Prox-Snap" 
VM_MEMORY=256 
VM_CPU=4 
VM_DISK_SIZE="500M" 
VM_NET="model=virtio,bridge=vmbr0,macaddr=BC:24:11:F8:BB:28" 
VM_NET_a="model=virtio,bridge=vmbr1,macaddr=BC:24:11:35:C1:A8" 
STORAGE_NAME="local-lvm" 
VM_IP="192.168.1.1" 
PROXMOX_NODE="PVE" 

# Create new VM
qm create $VM_ID --name $VM_NAME --memory $VM_MEMORY --net0 $VM_NET --net1 $VM_NET_a --cores $VM_CPU --ostype l26 --sockets 1 

# Remove default hard drive
qm set $VM_ID --scsi0 none 

# Rename the extracted img
rm /mnt/1TB_internal/x86_64_minipc/images/snap/openwrt.raw 
mv /mnt/1TB_internal/x86_64_minipc/images/snap/openwrt-x86-64-generic-ext4-combined.img /mnt/1TB_internal/x86_64_minipc/images/snap/openwrt.raw 

# Increase the raw disk
qemu-img resize -f raw /mnt/1TB_internal/x86_64_minipc/images/snap/openwrt.raw $VM_DISK_SIZE 

# Import the disk to the openwrt vm
qm importdisk $VM_ID /mnt/1TB_internal/x86_64_minipc/images/snap/openwrt.raw $STORAGE_NAME 

# Attach imported disk to VM
qm set $VM_ID --virtio0 $STORAGE_NAME:vm-$VM_ID-disk-0.raw [cite: 4, 5]

# Set boot disk
qm set $VM_ID --bootdisk virtio0 [cite: 5]
